[package]
name = "kvs"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
edition = "2018"

[dependencies]
structopt = { version = "0.3" }

[dev-dependencies]
predicates = "*"
assert_cmd = "*"
