[package]
name = "kvs"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
edition = "2018"

[dependencies]
structopt = { version = "0.3" }
snafu = "0.6"
speedy = { version = "0.6.0" }

[dev-dependencies]
predicates = "1.0.0"
assert_cmd = "0.11.0"
tempfile = "3.0.7"
walkdir = "2.2.7"
